-- 1
SELECT NOME, Ano FROM Filmes

-- 2
SELECT NOME, ANO FROM Filmes
ORDER BY ANO

-- 3
SELECT NOME, ANO, DURACAO FROM FILMES
WHERE NOME = 'De Volta para o Futuro'

--4
SELECT NOME, ANO, DURACAO FROM FILMES
WHERE ano = 1997

--5
SELECT NOME, ANO, DURACAO FROM FILMES
WHERE ano > 2000

--6
SELECT NOME, ANO, DURACAO FROM FILMES
WHERE Duracao > 100 AND Duracao < 150
ORDER BY Duracao

--7
SELECT ANO, COUNT(Ano) AS QUANTIDADE FROM FILMES
GROUP BY Ano
ORDER BY  QUANTIDADE DESC

--8
SELECT PRIMEIRONOME, ULTIMONOME, GENERO FROM Atores
WHERE Genero = 'm'

--9
SELECT PRIMEIRONOME, ULTIMONOME, GENERO FROM Atores
WHERE Genero = 'F'
ORDER BY PrimeiroNome

--10
SELECT F.NOME, G.GENERO
FROM FILMES F INNER JOIN FilmesGenero FG ON
(F.Id = FG.IdFilme) INNER JOIN Generos G ON
(FG.IdGenero = G.Id)

--11
SELECT F.NOME, G.GENERO
FROM FILMES F INNER JOIN FilmesGenero FG ON
(F.Id = FG.IdFilme) INNER JOIN Generos G ON
(FG.IdGenero = G.Id)
WHERE G.Genero = 'Mistério'

--12
SELECT F.NOME, A.PRIMEIRONOME, A.ULTIMONOME, E.PAPEL
FROM Filmes F INNER JOIN ElencoFilme E ON
(F.Id = E.IdFilme) INNER JOIN Atores A ON
(E.IdAtor = A.Id)





